create table test_data(success	int,
	      frame_id	int,
	      rho1	real,
	      theta1	real,
	      votes1	real,
	      rho2	real,
	      theta2	real,
	      votes2	real,      
	      lc	int,
	      msum	real,
	      x		int,
	      y		int,
	      umin	real,
	      umax	real,
	      nuh	real,
	      puh	real,
	      rcount	int,
	      test_id	int
	      );